### ISSUE TITLE
Flatcar boot leads to ignition error

### ISSUE THREAD

**Issue by baurmatt** [sardinasystems/fleeting-plugin-openstack#37]
Thanks for the plugin! I'm currently evaluating it and run into the following error when booting a Flatcar Stable (`4081.2.0`) image:

<img width="723" alt="image" src="https://github.com/user-attachments/assets/c3c5d251-c769-4de4-918f-03e36a5d4d24">

The reason seems to be an empty username:

<img width="721" alt="image" src="https://github.com/user-attachments/assets/190cbab7-d116-401b-b35e-132e9f68b509">

Here is my Gitlab Runner config.toml:

```toml
concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
name = "fleeting-test"
url = "https://gitlab.example.org/"
token = "xxxxxxxx"
executor = "docker-autoscaler"
shell = "bash"

[runners.docker]
disable_cache = true
image = "ubuntu:24.04"
volumes = ["/var/run/docker.sock:/var/run/docker.sock"]

[runners.autoscaler]
capacity_per_instance = 1
max_use_count = 2
max_instances = 3
plugin = "fleeting-plugin-openstack"

[runners.autoscaler.plugin_config]
cloud = "runner"
clouds_config = "/etc/gitlab-runner/clouds.yaml"
name = "scaling-runner-stack-id"
boot_time = "5m"
use_ignition = true  # enable injection of dynamic SSH key into Ignition config

[runners.autoscaler.plugin_config.server_spec]
name = "scaling-runner-%d"
description = "GitLab CI Docker runners with autoscaling"
tags = ["GitLab", "CI", "Docker", "Scaling"]
imageRef = "3d5e090d-999b-4698-a46d-de9ac5e1c908"
flavorRef = "7db7543b-c34b-4c67-ba90-9d8e169eadd0"
networks = [ { uuid = "bb1318d6-0d43-49e0-8598-8443bbac412c" } ]        # tenant network
security_groups = [ "71285538-4e81-48cf-a6ec-561885d4ae09" ]

[[runners.autoscaler.policy]]
idle_count = 1
scale_factor = 0.0
scale_factor_limit = 0
```
